export const COUNTRIES = [
  // Arab Countries
  { id: 'JO', name: 'الأردن', capital: 'عمان', flag: '🇯🇴', lat: 31.9539, lng: 35.9106, timezone: 'Asia/Amman', method: 'UmmAlQura' },
  { id: 'SA', name: 'المملكة العربية السعودية', capital: 'الرياض', flag: '🇸🇦', lat: 24.7136, lng: 46.6753, timezone: 'Asia/Riyadh', method: 'UmmAlQura' },
  { id: 'AE', name: 'الإمارات العربية المتحدة', capital: 'أبوظبي', flag: '🇦🇪', lat: 24.4539, lng: 54.3773, timezone: 'Asia/Dubai', method: 'Dubai' },
  { id: 'EG', name: 'مصر', capital: 'القاهرة', flag: '🇪🇬', lat: 30.0444, lng: 31.2357, timezone: 'Africa/Cairo', method: 'Egyptian' },
  { id: 'PS', name: 'فلسطين', capital: 'القدس الشريف', flag: '🇵🇸', lat: 31.7683, lng: 35.2137, timezone: 'Asia/Jerusalem', method: 'UmmAlQura' },
  { id: 'KW', name: 'الكويت', capital: 'مدينة الكويت', flag: '🇰🇼', lat: 29.3759, lng: 47.9774, timezone: 'Asia/Kuwait', method: 'Kuwait' },
  { id: 'QA', name: 'قطر', capital: 'الدوحة', flag: '🇶🇦', lat: 25.2854, lng: 51.5310, timezone: 'Asia/Qatar', method: 'Qatar' },
  { id: 'OM', name: 'سلطنة عمان', capital: 'مسقط', flag: '🇴🇲', lat: 23.5880, lng: 58.3829, timezone: 'Asia/Muscat', method: 'UmmAlQura' },
  { id: 'BH', name: 'البحرين', capital: 'المنامة', flag: '🇧🇭', lat: 26.2285, lng: 50.5860, timezone: 'Asia/Bahrain', method: 'UmmAlQura' },
  { id: 'IQ', name: 'العراق', capital: 'بغداد', flag: '🇮🇶', lat: 33.3152, lng: 44.3661, timezone: 'Asia/Baghdad', method: 'MuslimWorldLeague' },
  { id: 'SY', name: 'سوريا', capital: 'دمشق', flag: '🇸🇾', lat: 33.5138, lng: 36.2765, timezone: 'Asia/Damascus', method: 'MuslimWorldLeague' },
  { id: 'LB', name: 'لبنان', capital: 'بيروت', flag: '🇱🇧', lat: 33.8938, lng: 35.5018, timezone: 'Asia/Beirut', method: 'MuslimWorldLeague' },
  { id: 'YE', name: 'اليمن', capital: 'صنعاء', flag: '🇾🇪', lat: 15.3694, lng: 44.1910, timezone: 'Asia/Aden', method: 'UmmAlQura' },
  { id: 'MA', name: 'المغرب', capital: 'الرباط', flag: '🇲🇦', lat: 34.0209, lng: -6.8416, timezone: 'Africa/Casablanca', method: 'MuslimWorldLeague' },
  { id: 'DZ', name: 'الجزائر', capital: 'الجزائر', flag: '🇩🇿', lat: 36.7538, lng: 3.0588, timezone: 'Africa/Algiers', method: 'MuslimWorldLeague' },
  { id: 'TN', name: 'تونس', capital: 'تونس', flag: '🇹🇳', lat: 36.8065, lng: 10.1815, timezone: 'Africa/Tunis', method: 'MuslimWorldLeague' },
  { id: 'LY', name: 'ليبيا', capital: 'طرابلس', flag: '🇱🇾', lat: 32.8872, lng: 13.1913, timezone: 'Africa/Tripoli', method: 'MuslimWorldLeague' },
  { id: 'SD', name: 'السودان', capital: 'الخرطوم', flag: '🇸🇩', lat: 15.5007, lng: 32.5599, timezone: 'Africa/Khartoum', method: 'Egyptian' },
  { id: 'MR', name: 'موريتانيا', capital: 'نواكشوط', flag: '🇲🇷', lat: 18.0735, lng: -15.9582, timezone: 'Africa/Nouakchott', method: 'MuslimWorldLeague' },
  { id: 'SO', name: 'الصومال', capital: 'مقديشو', flag: '🇸🇴', lat: 2.0469, lng: 45.3182, timezone: 'Africa/Mogadishu', method: 'MuslimWorldLeague' },
  { id: 'DJ', name: 'جيبوتي', capital: 'جيبوتي', flag: '🇩🇯', lat: 11.5721, lng: 43.1456, timezone: 'Africa/Djibouti', method: 'MuslimWorldLeague' },
  { id: 'KM', name: 'جزر القمر', capital: 'موروني', flag: '🇰🇲', lat: -11.7172, lng: 43.2473, timezone: 'Indian/Comoro', method: 'MuslimWorldLeague' },

  // Islamic & Asian Countries
  { id: 'TR', name: 'تركيا', capital: 'أنقرة', flag: '🇹🇷', lat: 39.9334, lng: 32.8597, timezone: 'Europe/Istanbul', method: 'Turkey' },
  { id: 'MY', name: 'ماليزيا', capital: 'كوالالمبور', flag: '🇲🇾', lat: 3.1390, lng: 101.6869, timezone: 'Asia/Kuala_Lumpur', method: 'MuslimWorldLeague' },
  { id: 'ID', name: 'إندونيسيا', capital: 'جاكرتا', flag: '🇮🇩', lat: -6.2088, lng: 106.8456, timezone: 'Asia/Jakarta', method: 'Singapore' },
  { id: 'PK', name: 'باكستان', capital: 'إسلام آباد', flag: '🇵🇰', lat: 33.6844, lng: 73.0479, timezone: 'Asia/Karachi', method: 'Karachi' },
  { id: 'BD', name: 'بنغلاديش', capital: 'دكا', flag: '🇧🇩', lat: 23.8103, lng: 90.4125, timezone: 'Asia/Dhaka', method: 'Karachi' },
  { id: 'AZ', name: 'أذربيجان', capital: 'باكو', flag: '🇦🇿', lat: 40.4093, lng: 49.8671, timezone: 'Asia/Baku', method: 'MuslimWorldLeague' },
  { id: 'KZ', name: 'كازاخستان', capital: 'أستانا', flag: '🇰🇿', lat: 51.1694, lng: 71.4491, timezone: 'Asia/Almaty', method: 'MuslimWorldLeague' },
  { id: 'UZ', name: 'أوزبكستان', capital: 'طشقند', flag: '🇺🇿', lat: 41.2995, lng: 69.2401, timezone: 'Asia/Tashkent', method: 'MuslimWorldLeague' },
  { id: 'SG', name: 'سنغافورة', capital: 'سنغافورة', flag: '🇸🇬', lat: 1.3521, lng: 103.8198, timezone: 'Asia/Singapore', method: 'Singapore' },
  { id: 'IN', name: 'الهند', capital: 'نيودلهي', flag: '🇮🇳', lat: 28.6139, lng: 77.2090, timezone: 'Asia/Kolkata', method: 'Karachi' },
  { id: 'JP', name: 'اليابان', capital: 'طوكيو', flag: '🇯🇵', lat: 35.6762, lng: 139.6503, timezone: 'Asia/Tokyo', method: 'MuslimWorldLeague' },
  { id: 'CN', name: 'الصين', capital: 'بكين', flag: '🇨🇳', lat: 39.9042, lng: 116.4074, timezone: 'Asia/Shanghai', method: 'MuslimWorldLeague' },
  { id: 'KR', name: 'كوريا الجنوبية', capital: 'سيول', flag: '🇰🇷', lat: 37.5665, lng: 126.9780, timezone: 'Asia/Seoul', method: 'MuslimWorldLeague' },

  // Europe & Americas & Australia
  { id: 'GB', name: 'المملكة المتحدة', capital: 'لندن', flag: '🇬🇧', lat: 51.5074, lng: -0.1278, timezone: 'Europe/London', method: 'MuslimWorldLeague' },
  { id: 'US', name: 'الولايات المتحدة', capital: 'واشنطن', flag: '🇺🇸', lat: 38.9072, lng: -77.0369, timezone: 'America/New_York', method: 'NorthAmerica' },
  { id: 'CA', name: 'كندا', capital: 'أوتاوا', flag: '🇨🇦', lat: 45.4215, lng: -75.6972, timezone: 'America/Toronto', method: 'NorthAmerica' },
  { id: 'FR', name: 'فرنسا', capital: 'باريس', flag: '🇫🇷', lat: 48.8566, lng: 2.3522, timezone: 'Europe/Paris', method: 'MuslimWorldLeague' },
  { id: 'DE', name: 'ألمانيا', capital: 'برلين', flag: '🇩🇪', lat: 52.5200, lng: 13.4050, timezone: 'Europe/Berlin', method: 'MuslimWorldLeague' },
  { id: 'ES', name: 'إسبانيا', capital: 'مدريد', flag: '🇪🇸', lat: 40.4168, lng: -3.7038, timezone: 'Europe/Madrid', method: 'MuslimWorldLeague' },
  { id: 'IT', name: 'إيطاليا', capital: 'روما', flag: '🇮🇹', lat: 41.9028, lng: 12.4964, timezone: 'Europe/Rome', method: 'MuslimWorldLeague' },
  { id: 'NL', name: 'هولندا', capital: 'أمستردام', flag: '🇳🇱', lat: 52.3676, lng: 4.9041, timezone: 'Europe/Amsterdam', method: 'MuslimWorldLeague' },
  { id: 'SE', name: 'السويد', capital: 'ستوكهولم', flag: '🇸🇪', lat: 59.3293, lng: 18.0686, timezone: 'Europe/Stockholm', method: 'MuslimWorldLeague' },
  { id: 'NO', name: 'النرويج', capital: 'أوسلو', flag: '🇳🇴', lat: 59.9139, lng: 10.7522, timezone: 'Europe/Oslo', method: 'MuslimWorldLeague' },
  { id: 'DK', name: 'الدنمارك', capital: 'كوبنهاغن', flag: '🇩🇰', lat: 55.6761, lng: 12.5683, timezone: 'Europe/Copenhagen', method: 'MuslimWorldLeague' },
  { id: 'CH', name: 'سويسرا', capital: 'برن', flag: '🇨🇭', lat: 46.9480, lng: 7.4474, timezone: 'Europe/Zurich', method: 'MuslimWorldLeague' },
  { id: 'AT', name: 'النمسا', capital: 'فيينا', flag: '🇦🇹', lat: 48.2082, lng: 16.3738, timezone: 'Europe/Vienna', method: 'MuslimWorldLeague' },
  { id: 'BE', name: 'بلجيكا', capital: 'بروكسل', flag: '🇧🇪', lat: 50.8503, lng: 4.3517, timezone: 'Europe/Brussels', method: 'MuslimWorldLeague' },
  { id: 'BA', name: 'البوسنة والهرسك', capital: 'سراييفو', flag: '🇧🇦', lat: 43.8563, lng: 18.4131, timezone: 'Europe/Sarajevo', method: 'MuslimWorldLeague' },
  { id: 'AL', name: 'ألبانيا', capital: 'تيرانا', flag: '🇦🇱', lat: 41.3275, lng: 19.8187, timezone: 'Europe/Tirane', method: 'MuslimWorldLeague' },
  { id: 'RU', name: 'روسيا', capital: 'موسكو', flag: '🇷🇺', lat: 55.7558, lng: 37.6173, timezone: 'Europe/Moscow', method: 'MuslimWorldLeague' },
  { id: 'AU', name: 'أستراليا', capital: 'كانبرا', flag: '🇦🇺', lat: -35.2809, lng: 149.1300, timezone: 'Australia/Sydney', method: 'MuslimWorldLeague' },
  { id: 'NZ', name: 'نيوزيلندا', capital: 'ويلينغتون', flag: '🇳🇿', lat: -41.2865, lng: 174.7762, timezone: 'Pacific/Auckland', method: 'MuslimWorldLeague' },
  { id: 'BR', name: 'البرازيل', capital: 'برازيليا', flag: '🇧🇷', lat: -15.7975, lng: -47.8919, timezone: 'America/Sao_Paulo', method: 'MuslimWorldLeague' },
  { id: 'AR', name: 'الأرجنتين', capital: 'بوينس آيرس', flag: '🇦🇷', lat: -34.6037, lng: -58.3816, timezone: 'America/Argentina/Buenos_Aires', method: 'MuslimWorldLeague' },
  { id: 'ZA', name: 'جنوب أفريقيا', capital: 'بريتوريا', flag: '🇿🇦', lat: -25.7479, lng: 28.2293, timezone: 'Africa/Johannesburg', method: 'MuslimWorldLeague' },
  { id: 'NG', name: 'نيجيريا', capital: 'أبوجا', flag: '🇳🇬', lat: 9.0765, lng: 7.3986, timezone: 'Africa/Lagos', method: 'Egyptian' },
  { id: 'SN', name: 'السنغال', capital: 'داكار', flag: '🇸🇳', lat: 14.7167, lng: -17.4677, timezone: 'Africa/Dakar', method: 'MuslimWorldLeague' },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Jordan by default
